remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "GreenCodeAnalyzer"
description: "A VSCode Extension for Static Energy Analysis in Data Science"
